import type { ProjectileDamage } from "./projectileDamage";
import type { WeaponInfo } from "./weaponInfo";

export type Item = {
	category?: string;
	cost?: number;
	crafting?: any;
	name?: string;
	parent?: string;
	trade_price?: number;
	translation?: string;
	type?: string;
	description?: string;
	projectileDamage?: ProjectileDamage;
	experiencieReward?: number;
	stackSize?: number;
	weight?: number;
	durability?: number;
	weaponInfo?: WeaponInfo;
	toolInfo?: any;
	moduleInfo?: any;
	schematicName?: string;
	upgradeInfo?: any;
	armorInfo?: any;
	movementSpeedReduction?: number;
	drops?: any;
	structureInfo?: any;
	wikiVisibility?: boolean;
	learn?: any;
	walkerInfo?: any;
	onlyDevs?: boolean;
};
